import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // @repo/db ships raw TypeScript (main: ./src/index.ts) and is generated by
  // Prisma 7 — Next must transpile it instead of treating it as a built dep.
  transpilePackages: ["@repo/db"],
};

export default nextConfig;
