services:
  postgres:
    image: postgres:17-alpine
    container_name: stack-grill-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: stack_grill
      POSTGRES_PASSWORD: stack_grill_secret
      POSTGRES_DB: stack_grill
      PGPORT: 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
